services:
  # Front‑end React/Vite déployé en site statique
  - type: web
    runtime: static
    name: literate-disco-front
    plan: starter
    branch: main
    repo: https://github.com/yogatypic/literate-disco
    rootDir: .
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    envVars:
      - key: VITE_API_URL
        value: "https://prompt-ultime.onrender.com"

  # Back‑end Python/FastAPI déployé en Web Service
  - type: web
    runtime: python
    name: prompt-ultime-api
    plan: starter
    rootDir: src
    buildCommand: |
      if [ ! -x /opt/render/project/poetry/bin/poetry ]; then
        curl -sSL https://install.python-poetry.org | python3 -
      fi
      export PATH="/opt/render/project/poetry/bin:$PATH" && poetry install --no-dev
    startCommand: |
      export PATH="/opt/render/project/poetry/bin:$PATH" && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

