services:

* type: static\_site
  name: literate-disco-front
  env: node
  plan: free
  branch: main
  repo: [https://github.com/yogatypic/literate-disco](https://github.com/yogatypic/literate-disco)
  rootDir: .
  buildCommand: "npm install && npm run build"
  staticPublishPath: build
  envVars:

  * key: VITE\_API\_URL
    value: "[https://prompt-ultime.onrender.com](https://prompt-ultime.onrender.com)"

* type: web\_service
  name: prompt-ultime-api
  env: python
  plan: free
  rootDir: src
  buildCommand: |
  if \[ ! -x /opt/render/project/poetry/bin/poetry ]; then
  curl -sSL [https://install.python-poetry.org](https://install.python-poetry.org) | python3 -
  fi
  export PATH="/opt/render/project/poetry/bin:\$PATH" && poetry install --no-dev
  startCommand: |
  export PATH="/opt/render/project/poetry/bin:\$PATH" && poetry run uvicorn main\:app --host 0.0.0.0 --port \$PORT
  envVars:

  * key: PYTHON\_VERSION
    value: "3.11"

